#!/bin/sh
#
# Script:            make_depends
# Created by         Jeremie Gressier
# Usage              make_depends lower|upper filename
#
# Description:		
#
# This script parses f90 files in order to extract
# file dependencies (MODULE). It can handle:
#      use ok1                ! comment
#      use ok2, ok3           ! comment
#      use ok4, only not_me   ! comment
#      use ok5, &             ! comment
#          ok6                ! comment
#
# and writes
#
#  $(OD)/test.$(o): test.f90 \
#                          $(OD)/ok1.$(o)    \
#                          $(OD)/ok2.$(o)    \
#                          $(OD)/ok3.$(o)    \
#                          $(OD)/ok4.$(o)    \
#                          $(OD)/ok5.$(o)    \
#                          $(OD)/ok6.$(o)    \
#
# Caution: Problems have happened with comments containing no basic letters
# which can be not recognized by regexp wildcards (.*)

#-----------------------------------------------------------------
case $1 in
  lower) trchangecase="A-Z a-z" ;;
  upper) trchangecase="a-z A-Z" ;;
  *)     echo Panic: unknown option :$1: ; exit 1 ;;
esac
shift

USE=$(echo use | tr $trchangecase)

sedrmcomment="s/ *!.*//"
sededithead="s/^ *$USE /    \$(PRJINCDIR)\\//"
sededittail="s/ *$/.\$(MODEXT) \\\\/"

#-----------------------------------------------------------------
# try to get optional ROOT folder
ROOTDIR=${1:-.}

TARGET=$ROOTDIR/depends.make

#-----------------------------------------------------------------
echo Building module dependencies in $TARGET

rm $TARGET 2> /dev/null

echo "# This file has been created automatically"    > $TARGET
echo "# It can be overwritten"                      >> $TARGET
echo "# (manual modifications are not recommended)" >> $TARGET

for fic in $(find $ROOTDIR -name '*.f90' | grep -v '/.#') ; do

  basename=$(basename $fic .f90)

  moduledepend=$(
    grep -i '^ *use ' $fic |
      tr   $trchangecase   |
      sed "$sedrmcomment;$sededithead;$sededittail"
    )
  #

  # MODULE

  if [ -n "$(grep -i '^ *module ' $fic)" ] ; then
    modulebase=$(basename $fic .f90 | tr $trchangecase)
    echo $modulebase.source:=$fic >> $TARGET
    echo $modulebase.object:=$basename.o >> $TARGET
    echo $basename.target: '$(PRJINCDIR)/'$modulebase.'$(MODEXT)'  >> $TARGET
    echo >> $TARGET
    echo ${modulebase}.'$(MODEXT): $(PRJINCDIR)/'${modulebase}.'$(MODEXT)' >> $TARGET
    echo '$(PRJINCDIR)/'${modulebase}.'$(MODEXT)': $fic \\ >> $TARGET
    echo -e "${moduledepend:-\c}" >> $TARGET
    echo >> $TARGET
  fi

  # OBJET

  #echo $modulebase.objsrc:=$fic >> $TARGET
  echo '$(PRJOBJDIR)/'$basename.o: $fic \\   >> $TARGET
  echo -e "${moduledepend:-\c}" >> $TARGET
  echo >> $TARGET

done

